apiVersion: v1
kind: Secret
metadata:
  name: projectpulse-secret
type: Opaque
data:
  # Base64 encoded secrets (example values for local cluster testing)
  APP_KEY: "YmFzZTY0OlZsdFEzb1ErVzBXdkQyTzNEM3M0YjhHNWE2YjdjOGQ5ZTBmMWEyYjNjNGQ9"
  DB_PASSWORD: "c2VjcmV0cGFzc3dvcmQ="
  GEMINI_API_KEY: "WV9URVNUX0dFTUlOSV9BUElfS0VZ"
